#!/usr/bin/env php
<?php

declare(strict_types=1);

spl_autoload_register(function ($class) {
    $file = __DIR__ . '/src/' . str_replace('\\', '/', $class) . '.php';
    if (file_exists($file)) {
        require $file;
    }
});

try {
    $repository = new TaskRepository();
    $app = new CliApplication($repository);
    $app->run($argv);
} catch (Throwable $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}